### ISSUE TITLE
Flag to skip parsing exports

### ISSUE THREAD

**Issue by LarsDenBakker** [guybedford/es-module-lexer#10]
For my use case I only need the imports. Do you think it would be much faster if there was a flag to skip parsing the exports? At least it would prevent some syntax errors, since parsing exports is a lot more complex than imports.

**Comment by guybedford** [comment]
I don't think it would improve performance as we still need to tokenize the whole source (imports can be at the end) and skipping the export routine is a minor saving.

Let's fix the export destructing bugs though, and continue to track that in https://github.com/guybedford/es-module-lexer/issues/2.
