### ISSUE TITLE
RuntimeError: memory access out of bounds

### ISSUE THREAD

**Issue by jackyking-cn** [guybedford/es-module-lexer#106]
I use vite，when run build script，some time success，some time throw error:
![824fb99528164dcab4b62f896009725d](https://user-images.githubusercontent.com/1309499/158562307-06d54e41-ddca-4efb-ab6f-1dd4af7da245.PNG)

vite use parse method in es-module-lexer@0.9.3 

it is bug of es-module-lexer or my code?

**Comment by guybedford** [comment]
Thanks for posting - please try using the latest 0.10.0 es-module-lexer version.

Then, if you are still seeing the problem, sharing a replication of the exact case, this means an isolated replication of the Wasm parse itself, without Vite.

**Comment by jackyking-cn** [comment]
It‘s ok when upgraded to es-module-lexer@0.10.0, Thanks lot.
