### ISSUE TITLE
Importing ASM version breaks TypeScript

### ISSUE THREAD

**Issue by JacobMGEvans** [guybedford/es-module-lexer#115]
```ts
import { parse } from 'es-module-lexer/js';
```
`Cannot find module 'es-module-lexer/js' or its corresponding type declarations.ts(2307)`

**Comment by guybedford** [comment]
I'd be happy to update the declaration definitions. It might just need a `dist/lexer.asm.js` reexporting the types.

**Comment by guybedford** [comment]
(PR would be helpful, otherwise I'll leave this up for now)

**Comment by JacobMGEvans** [comment]
If I find a spare moment 😄
