### ISSUE TITLE
losing comment when parse dynamic import  in >0.9.3

### ISSUE THREAD

**Issue by l1shu** [guybedford/es-module-lexer#117]
```
const { init, parse } = require('es-module-lexer');

const code = `
const routes = {
  a: () => import(/* webpackChunkName: "a" */ '@src/a/view.tsx'),
}
`;

(async () => {
  // either await init, or call parse asynchronously
  // this is necessary for the Web Assembly boot
  await init;

  const [imports, exports] = parse(code);

  console.log(imports);
})();
```

in 0.9.3:
<img width="565" alt="image" src="https://user-images.githubusercontent.com/48285873/174779365-3ab2b808-f37a-4d88-8ebd-a18cd2daf05f.png">

\>0.9.3:
<img width="530" alt="image" src="https://user-images.githubusercontent.com/48285873/174779456-391c301f-6857-4b91-b479-ffe3304e8242.png">

when the version >0.9.3, it will losing the comment

**Comment by guybedford** [comment]
@l1shu this is correct and was a change made and reflected in the documentation. Instead `ss` and `se` can be used to extract the comment information.

**Comment by l1shu** [comment]
> @l1shu this is correct and was a change made and reflected in the documentation. Instead `ss` and `se` can be used to extract the comment information.

thanks for replying
