### ISSUE TITLE
CommonJS is missing?

### ISSUE THREAD

**Issue by evanw** [guybedford/es-module-lexer#122]
I wanted to try out this package so I followed [the instructions](https://github.com/guybedford/es-module-lexer#usage). However, that fails with the following error:

```
Error: Cannot find module './node_modules/es-module-lexer/dist/lexer.cjs'
```

This is because [`lexer.cjs` wasn't published](https://unpkg.com/browse/es-module-lexer@1.0.0/dist/). Perhaps the instructions for CommonJS could be removed if this is intended to be an ESM-only package?

**Comment by guybedford** [comment]
I just happened to publish 1.0 yesterday evening and didn't run a full build which missed this. It should work now with the 1.0.1 release.
