### ISSUE TITLE
Syntax error reported w/ default export

### ISSUE THREAD

**Issue by robrez** [guybedford/es-module-lexer#138]
Sorry, I don't have a great, minimal reproduction example.. I depend on `es-module-lexer` transitively from [@web/dev-server](https://github.com/modernweb-dev/web/blob/master/packages/dev-server-core/package.json#L64)

Since `1.0.4`, started receiving a syntax error for code that looks like this:

`foo.js`

```js
const css = String.raw;
export default css`:host { solid 1px black }`;
```

`bar.js`

```js
import foo from '@org/foo.js';`
```

`@web/dev-server` reports the the error as:

```bash
Error while transforming node_modules\@org/foo.js: Syntax error

  1 | const css = String.raw;
  2 | export default css`:host { solid 1px black }`;
> 3 |
    | ^
```

Note that if I change the code, this works:

```js
const css = String.raw;
const blah = css`:host { solid 1px black }`;
export default blah;
```

My remedial action has been to pin `es-module-lexer` in my package.json... `^1.0.0 <=1.0.3`

**Comment by guybedford** [comment]
Thanks for sharing the case and version, that helps a lot. Fixed in 1.0.5.
