### ISSUE TITLE
Fails to parse `export default{}` (no space after `default`)

### ISSUE THREAD

**Issue by sapphi-red** [guybedford/es-module-lexer#140]
When the following code is passed, `es-module-lexer` throws an error.
```js
export default{};
```

This happens from 1.0.5. It worked with 1.0.4 and before.

reproduction: https://stackblitz.com/edit/node-rvshud?file=index.js,input.js

Real world code: https://github.com/nextapps-de/flexsearch/blob/9abb781357f04e7db8529654c6941009771f4bf1/dist/module/lang/latin/advanced.js

**Comment by guybedford** [comment]
Fix released in 1.1.0.

**Comment by sapphi-red** [comment]
Thank you!
