### ISSUE TITLE
Parse error for import.meta.env

### ISSUE THREAD

**Issue by IanVS** [guybedford/es-module-lexer#142]
We are using this package in storybook's vite builder, and found that we get a parse error for expressions like `import.meta.env.STORYBOOK_ENV`, which is the syntax that vite uses for environment variables.

**Comment by guybedford** [comment]
@IanVS can you please share an exact test case here for what is not parsing?

I just tried `parse(`import.meta.env.STORY_BOOK_ENV`)` and this is working fine for me.

**Comment by IanVS** [comment]
Thanks for taking a look. I was hoping it would be something clear cut, but I guess not. I'll dig in and let you know what I find.

**Comment by IanVS** [comment]
Sorry for the noise, this turned out to be an issue on our end.
