### ISSUE TITLE
Inconsitency in i.s and i.e when parsing imports

### ISSUE THREAD

**Issue by A-Shleifman** [guybedford/es-module-lexer#144]
Thank you for the plugin!

Found the following inconsistency/bug:

```ts
import test from 'test'; // 👈 parsed as { n: 'test', s: 19: e: 23 }
//                                                        ^^^ length: 4

import('test'); // 👈 parsed as { n: 'test', s: 34: e: 40 }
//                                               ^^^ length: 6
```

When parsing static imports, {s,e} do not include quotes, while they are included when dynamic imports are parsed.

[Demo](https://stackblitz.com/edit/node-wyyrby?file=index.js)

**Comment by guybedford** [comment]
This is by design, since dynamic import is an expression, and therefore includes the quotes, while static import is a direct string.
