### ISSUE TITLE
v1.1.1 fails with export specifier in string

### ISSUE THREAD

**Issue by bluwy** [guybedford/es-module-lexer#148]
In v1.1.1, es-module-lexer errors when parsing these valid JS code:

```js
export default "export default a"
```

```js
export default "export default 'a'"
```

```js
export default "export function foo() {}"
```

```js
export default "export function foo() {return bar}"
```

Here's a [stackblitz repro](https://stackblitz.com/edit/node-sargug?file=index.js), installing v1.1.0 instead fixes the issue. From the patterns, it looks like it's parsing the export specifier within the string.

Stumbled upon this in Vite: https://github.com/vitejs/vite/pull/12036

**Comment by guybedford** [comment]
Thanks for reporting, fix in https://github.com/guybedford/es-module-lexer/pull/149.
