### ISSUE TITLE
undocumented `.d` -2

### ISSUE THREAD

**Issue by loynoir** [guybedford/es-module-lexer#151]
https://github.com/guybedford/es-module-lexer/blob/992d35da712a7a37af165114a564775e412e90ed/README.md?plain=1#L125-L127

https://github.com/guybedford/es-module-lexer/blob/992d35da712a7a37af165114a564775e412e90ed/src/lexer.ts#L54-L58

**Comment by guybedford** [comment]
Added in https://github.com/guybedford/es-module-lexer/commit/36ce8f0162c435b722f16c2a41804ce4a76470d5.
