### ISSUE TITLE
Import attributes

### ISSUE THREAD

**Issue by matthewp** [guybedford/es-module-lexer#165]
https://github.com/guybedford/es-module-lexer/pull/74 added information about import assertions, would it be simple enough to do the same for the newer import attributes?

**Comment by matthewp** [comment]
Oh I'm sorry, this was already added in https://github.com/guybedford/es-module-lexer/pull/150

**Comment by guybedford** [comment]
Yes, I'm aiming to keep this project up to date, since es-module-shims will be continuing to support new modules features. Issues and PRs always welcome @matthewp!
