### ISSUE TITLE
methods named import incorrectly detected 

### ISSUE THREAD

**Issue by LarsDenBakker** [guybedford/es-module-lexer#17]
Here I am again :)

```js
class A {
  import() {

 }
}
```

Is detected as a dynamic import rather than a method. The same goes for:

```js
const a = {
  import() {

 }
}
```

**Comment by guybedford** [comment]
These cases are working fine for me in a unit test... can you share an exact replication?

**Comment by guybedford** [comment]
(Existing tests for similar cases can be found at https://github.com/guybedford/es-module-lexer/blob/master/test/_unit.js#L140)

**Comment by LarsDenBakker** [comment]
I added a failing test: https://github.com/guybedford/es-module-lexer/pull/18
