### ISSUE TITLE
Syntax error when exporting destructured variables

### ISSUE THREAD

**Issue by LarsDenBakker** [guybedford/es-module-lexer#2]
This gives a syntax error, but it runs fine in chrome:
```js
export const { a, b } = foo;
```

**Comment by guybedford** [comment]
It would be worth checking against the latest master as I've made some changes today.

Otherwise a fix is very welcome, I expect it is because it is not exiting the `export ...` parse at the position before `{` resulting in an unmatched brace error.

**Comment by LarsDenBakker** [comment]
Yeah still giving an error, I'll see if I can make a fix.

**Comment by guybedford** [comment]
Thanks, I would take a look at it but I'm currently working on https://github.com/guybedford/es-module-lexer/issues/3!

**Comment by guybedford** [comment]
Fixed in #11.
