### ISSUE TITLE
String with a newline causes a parse error

### ISSUE THREAD

**Issue by LarsDenBakker** [guybedford/es-module-lexer#25]
```
  const var = '\n\';
```

causes a parse error

**Comment by zaygraveyard** [comment]
Your code sample is not valid JS, you are escaping the closing single quote.
Does the following cause a parse error?
```js
  const var = '\n';
```

**Comment by LarsDenBakker** [comment]
You're right, that's a typo sorry. Without the \ it still causes a parse error. See: https://github.com/guybedford/es-module-lexer/pull/26

**Comment by zaygraveyard** [comment]
Looks like in your test you are using
```js
    const source = `
      const foo = '\n';
      import './a.js';
    `;
```
Which gives the parser
```js
      const foo = '
';
      import './a.js';
```
Which is invalid JS
But trying
```js
    const source = `
      const foo = '\\n';
      import './a.js';
    `;
```
Parses ok

**Comment by LarsDenBakker** [comment]
My bad, I was debugging why something was failing after compilation to es5. console.log showed that babel output regular strings with \n, but after looking further it does print them with escape characters so that's not the issue. I'll look further.
