### ISSUE TITLE
Experimental Wasm Conversion

### ISSUE THREAD

**Issue by guybedford** [guybedford/es-module-lexer#3]
While the times for parsing are great when warmed up in the optimizer, this project heavily relies on cold performance because this is boot-time code analysis.

This is exactly the sort of reason to look into using Wasm.

I've started a branch to investigate this further, hope to have some results this week.

**Comment by LarsDenBakker** [comment]
This is pretty interesting, what language do you plan on writing it in?

**Comment by guybedford** [comment]
It has to be very lightweight (under 8KiB), so C is the obvious choice.

Nearly finished the conversion, hopefully should have a PR up tomorrow.

Because it's an exact port the current bugs should still apply to it, so don't let this stop any fixes.

**Comment by guybedford** [comment]
PR at https://github.com/guybedford/es-module-lexer/pull/7.

**Comment by guybedford** [comment]
Released in 0.3.0
