### ISSUE TITLE
Error lexing export with comment between variable names and equal sign

### ISSUE THREAD

**Issue by LarsDenBakker** [guybedford/es-module-lexer#39]
`graphql` generates code like this: https://unpkg.com/browse/graphql@14.5.8/type/definition.mjs#LC752 which throws an error in the lexer.

It looks like it's the comment between the variable name and the equals sign that's causing the issue.

This throws as well:

```js
export var GraphQLEnumType /* <T> */ = /*#__PURE__*/ function () {
```

and 

```js
export var GraphQLEnumType /* <T> */ = function () {
```

**Comment by guybedford** [comment]
@LarsDenBakker did you try this with the very latest release of es-module-lexer (0.3.13)? I just tested it out on this version and it seems to work ok there.

**Comment by LarsDenBakker** [comment]
Looks like we were still on an older version, sorry about that!
