### ISSUE TITLE
Doesn't work with imports with non breakable space

### ISSUE THREAD

**Issue by LarsDenBakker** [guybedford/es-module-lexer#42]
After an interesting debugging session, I found out that some imports in some files weren't detected because they contained non breakable spaces (char 160). These are apparently valid to use in javascript.

See a reproduction here: https://jsbin.com/cekivufibu/edit?html,output

**Comment by guybedford** [comment]
Yes, I didn't want to support all the character variants because it seemed unnecessary - did not know anyone actually relied on these!

Happy to fix to spec, will post a PR now.

**Comment by guybedford** [comment]
Fix released in 0.3.14.

**Comment by LarsDenBakker** [comment]
They probably used it unintentionally, but its a silent error.
