### ISSUE TITLE
No valid exports main found

### ISSUE THREAD

**Issue by soelen** [guybedford/es-module-lexer#46]
Recently the latest version of [es-dev-server](https://github.com/open-wc/open-wc/tree/master/packages/es-dev-server) doesn't seem to work anymore; it complains about a missing export or so I assume at least

```
{
  ...
  "dependencies": {
    "es-dev-server": "^1.40.0"
  }
}
```
```
npx es-dev-server
No valid exports main found for '...node_modules/es-module-lexer'
```

**Comment by guybedford** [comment]
Thanks, I've released a 0.3.17 which reverts the package.json changes here.
