### ISSUE TITLE
Memory out of bounds error

### ISSUE THREAD

**Issue by LarsDenBakker** [guybedford/es-module-lexer#52]
Code patterns like this:

```js
const foo = };
const bar = {};
```

throw a memory access out of bounds error. 

See this repo: https://jsbin.com/zuhirolegi/edit?html,output

**Comment by guybedford** [comment]
Thanks, this is important as it breaks the state for future parses!!!

Was a standard integer overlfow issue, fixed and released in 0.3.25.

**Comment by LarsDenBakker** [comment]
Thanks for resolving so quickly :)
