### ISSUE TITLE
node exports?

### ISSUE THREAD

**Issue by daKmoR** [guybedford/es-module-lexer#54]
hey,

I remember we added and then reverted exports to the package.json... 
I'm not sure however what the reason was?

Right now I am trying to import es-module-lexer in a node 14+ type="module" package and I need to do
```js
import { init, parse } from 'es-module-lexer/dist/lexer.js';
```

would be nice if I could just do
```js
import { init, parse } from 'es-module-lexer';
```

this could be archived with an export map that may look something like this
```js
"exports": {
  ".": {
     "require": "dist/lexer.cjs",
     "default": "dist/lexer.js",
  }
}
```

so the question is could we add it? and if not why was that again 😅

**Comment by guybedford** [comment]
@daKmoR yes this can be reconsidered now indeed.

Out of interest, why don't you just do:

```js
import lexer from 'es-module-lexer';
const { init, parse } = lexer;
```

for this case? The Node.js error message should be guiding this usage I believe.

**Comment by daKmoR** [comment]
intuitively I go for the `import { foo }` syntax... 

doing the default import and destructure into variables always feels like a forced step/workaround...
but yeah for node code it should not matter that much...
Still everything that is not intuitive will always produce friction so if I can clean it up or help to do so - I try 🤗

**Comment by guybedford** [comment]
Yeah we should ship this feature now.

**Comment by guybedford** [comment]
Note it is:

```js
"exports": {
  "require": "./dist/lexer.cjs",
  "default": "./dist/lexer.js"
}
```

**Comment by daKmoR** [comment]
want me to create a pull request?

**Comment by guybedford** [comment]
Sure, I’ll merge and release when I can.
