### ISSUE TITLE
Fallback to global atob in lexer.js

### ISSUE THREAD

**Issue by JYone3A** [guybedford/es-module-lexer#57]
Hi,

starting with Node 12.20 I suddenly got a weird error as soon as the dynamic `import` command was called from an ES Module (importing, I assume, a non-ESM module and therefore the lexer was used to get the static exports):
```
[CompileError: WebAssembly.compile(): unknown section code #0x65 @+266]
```

The problem was that in [lexer.js:46](https://github.com/guybedford/es-module-lexer/blob/master/src/lexer.js#L46) a global `atob` function is used if present. While the actual bug was on my side (the global `atob` did convert to a utf8 string instead of binary), I just wonder why that fallback is even implemented? It seems like in previous versions, it was the other way around - if `Buffer` was present, that was used and not a global `atob` function, but I don't really get why that was changed in  #28.

Again, the bug was on my side, it was just pretty confusing initially as I did not think something like setting `global.atob` could break such a fundamental node functionality like `await import()`.

Also, the error message did not really help as no stack trace was available, so maybe the `WebAssembly.compile()` could be wrapped in a try/catch?

**Comment by guybedford** [comment]
The justification is that for other JS envs, like Deno, atob can work fine without needing to bring in the Node.js Buffer shim.

But I agree it is unfortunate that a global atob can change the behaviour.

Out of interest, what changes were present to the global for this to happen in your environment? I'm a little unclear on

**Comment by guybedford** [comment]
I added a fix for this in https://github.com/guybedford/es-module-lexer/pull/58.

**Comment by JYone3A** [comment]
Thanks!

```javascript
global.atob = s => Buffer.from(s, 'base64').toString('utf8');

import('fetch').then(console.log, console.error)
```

this is enough to trigger the problem:
```bash
$ node test.mjs 
[CompileError: WebAssembly.compile(): unknown section code #0x65 @+266]
```

Its fine if the `global.atob` is changed after the first `import()` command is executed.
