### ISSUE TITLE
Windows paths not working

### ISSUE THREAD

**Issue by codepunkt** [guybedford/es-module-lexer#69]
Windows paths seem to be not working.
I'm running a [vite](https://github.com/vitejs/vite) build that uses `es-module-lexer` to parse imports and then uses the `n` field to check whether imports are possible or not.

```js
const { init, parse } = require('es-module-lexer')

;(async () => {
  await init

  const [imports, exports] = parse(
    'import es from "D:\\projects\\wilson\\docs\\src\\pages\\index.tsx"'
  )
  console.log(imports)
})()
```

logs

```js
[
  {
    n: 'D:projectswilsondocssrcpagesindex.tsx',
    s: 16,
    e: 59,
    ss: 0,
    se: 60,
    d: -1
  }
]
```

**Comment by guybedford** [comment]
@codepunkt this is actually correct - the same will apply if you try to load paths like this in the browser which interprets `D:` as a URL scheme not a path. Instead you should import `file:///D:/projects/...`.

**Comment by codepunkt** [comment]
@guybedford I'm not sure I understand. I'm not trying to load anything in the browser. I have an import with an absolute path in Nodejs on windows. Those work, but es-module-lexer returns the path without any backslashes.

**Comment by guybedford** [comment]
@codepunkt Node.js is the same since ES modules run as file URLs even in Node.js - `import 'D:\\'` is interpreted as a scheme not a drive.

**Comment by codepunkt** [comment]
Ahh, I see. Thanks Guy! 😊

**Comment by guybedford** [comment]
No problem!
