### ISSUE TITLE
Can not parse `export type {} from 'xxx'`

### ISSUE THREAD

**Issue by qmhc** [guybedford/es-module-lexer#72]
When I use:

```ts
import type { Test } from './test'

export type { Test }
```

it can be parsed, but not:

```ts
export type { Test } from './test'
```

**Comment by guybedford** [comment]
The lexer is only designed to support JavaScript not TypeScript. If you need TypeScript support that should probably be implemented as a fork of this project as I don't want to deviate the design goals here towards that currently.

**Comment by qmhc** [comment]
Thanks for your reply, but I am not good at c lang, maybe I will try in the future.
