### ISSUE TITLE
comments can trick the lexer

### ISSUE THREAD

**Issue by LarsDenBakker** [guybedford/es-module-lexer#8]
I'm seeing a couple of scenarios where comments can throw off the lexer:
```js
import/* 'a' */ 'b';
```

makes the lexer stop at `/*`

```js
import /* 'a' */ 'b';
```
makes the lexer stop at the second `'` inside the comment.

```js
export {
  a,
  // b,
  /* c */ d
};
```

comments inside an export statement also cause syntax errors

If I understand it correctly, calls to `commentWhitespace` should walk over whitespace and comments in the source code, so we should update it to properly recognize all sources of white space and comments?

**Comment by guybedford** [comment]
Thanks, these failure cases are a huge help to know. The fixes should be straightforward. Will take a look tomorrow.

**Comment by guybedford** [comment]
Fix included in the Wasm implementation at https://github.com/guybedford/es-module-lexer/pull/7/commits/a9dfc342db6ccaf4b47de07af5d43bf4d2a42ad5.
