### ISSUE TITLE
Bad Naming Convention

### ISSUE THREAD

**Issue by Heartnett** [guybedford/es-module-lexer#83]
ss? se? n? d? Regardless of the typescript typings and documentation, this naming convention reduces code readability. Please consider using proper names such as "moduleName" instead of "n".

**Comment by guybedford** [comment]
This project was originally designed and is primarily maintained as the base for es-module-shims, which is designed to be a load-critical shim and hence every byte saving matters. That is why all unnecessary byte overhead in the source of this library is removed to ensure it is as minimal as possible. Object minification is a common feature of build optimization, just done manually here.

I'd highly suggest working on your tone when posting issues if you want to get a positive response. For example, leading with a question that is a sentence such as "Can you explain why you use names like ss and se" would immediately come across less rude and be less likely to get a rude response.
