### ISSUE TITLE
feat: support stringify?

### ISSUE THREAD

**Issue by imcuttle** [guybedford/es-module-lexer#99]
In my screen, I need to `stringify` the result of `parse`.

```js
const [import] = parse(`
import a from 'a'
`)

stringify(import[0]) // => import a from 'a'
```

**Comment by guybedford** [comment]
Because this project is not a parser, stringification is a non-goal.

You can use a system like magic-string for source range rewriting though. See eg https://github.com/rich-harris/magic-string, which is used as the basis of source rewriting in RollupJS.
